//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountRole
    {
        public int ID { get; set; }
        public int ID_Role { get; set; }
        public int ID_Account { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Role Role { get; set; }
    }
}
