// <auto-generated />
namespace WebCK.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class data_v1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(data_v1));
        
        string IMigrationMetadata.Id
        {
            get { return "202005110856173_data_v1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
